# Generated by Django 5.1.1 on 2024-09-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contig', models.CharField(max_length=200, unique=True)),
                ('sequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('strand', models.CharField(blank=True, max_length=1, null=True)),
                ('phase', models.CharField(blank=True, max_length=1, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='viewer.sequence')),
            ],
        ),
    ]
