# Generated by Django 5.1.1 on 2024-10-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='feature_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genome',
            name='repeat_region_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genome',
            name='total_length',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sequence',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RepeatRegionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_region_methods', to='viewer.genome')),
            ],
            options={
                'unique_together': {('genome', 'method')},
            },
        ),
    ]
