# Generated by Django 5.1.1 on 2024-09-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
