# Generated by Django 5.1.1 on 2024-10-03 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_genome_feature_count_genome_repeat_region_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='cas_gene_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genome',
            name='has_crispr_repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CasGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas_genes', to='viewer.genome')),
            ],
            options={
                'unique_together': {('genome', 'name')},
            },
        ),
    ]
