# Generated by Django 5.1.1 on 2024-09-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_feature_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NucleotideData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nucleotide_data', to='viewer.sequence')),
            ],
            options={
                'unique_together': {('sequence', 'position')},
            },
        ),
    ]
