# Generated by Django 5.1.1 on 2024-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_genome_cas_gene_count_genome_has_crispr_repeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatregionmethod',
            name='repeats',
            field=models.ManyToManyField(related_name='repeat_methods', to='viewer.feature'),
        ),
    ]
