# Generated by Django 5.1.1 on 2024-09-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_nucleotidedata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nucleotidedata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nucleotidedata',
            name='data_source',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='nucleotidedata',
            unique_together={('sequence', 'position', 'data_source')},
        ),
    ]
