# Generated by Django 5.1.1 on 2024-10-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_repeatregionmethod_repeats'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneInfluence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=255, unique=True)),
                ('coefficient', models.FloatField()),
                ('p_value', models.FloatField()),
            ],
        ),
    ]
