# Generated by Django 5.1.1 on 2024-09-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_nucleotidedata_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NucleotideInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_position', models.PositiveIntegerField()),
                ('to_position', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='viewer.sequence')),
            ],
            options={
                'unique_together': {('sequence', 'from_position', 'to_position')},
            },
        ),
    ]
