# Generated by Django 5.1.1 on 2024-10-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_geneinfluence'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneinfluence',
            name='full_equation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geneinfluence',
            name='is_cas_gene',
            field=models.BooleanField(default=False),
        ),
    ]
