# Generated by Django 5.1.1 on 2024-09-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_nucleotideinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_position', models.IntegerField()),
                ('to_position', models.IntegerField()),
                ('weight', models.FloatField()),
                ('from_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_from', to='viewer.sequence')),
                ('to_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_to', to='viewer.sequence')),
            ],
        ),
        migrations.DeleteModel(
            name='NucleotideInteraction',
        ),
    ]
