# Generated by Django 5.1.1 on 2024-10-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_geneinfluence_full_equation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneinfluence',
            name='gene_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='geneinfluence',
            unique_together={('gene_name',)},
        ),
    ]
