# Generated by Django 5.1.1 on 2024-09-26 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_interaction_delete_nucleotideinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSummaryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=100)),
                ('mean_value', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_stats', to='viewer.feature')),
            ],
            options={
                'unique_together': {('feature', 'data_source')},
            },
        ),
    ]
