# Generated by Django 5.1.1 on 2024-10-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_geneinfluence_gene_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneinfluence',
            name='p_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
